version: 1.2
workflows:
   - subclass: NFL
     primaryDescriptorPath: /nextflow.config
     readMePath: /README.md
     name: fastqc
     topic: Quality control of FASTQ data with single report
   - subclass: WDL
     name: hello
     primaryDescriptorPath: /hello.wdl
     authors:
       - orcid: 0009-0008-6452-9030
       - orcid: 0000-0002-0396-0256	
